# Generated by Django 4.2.7 on 2024-03-08 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='id телеграм аккаунта'),
        ),
    ]
