# Generated by Django 4.2.7 on 2024-03-03 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HabitPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='название места')),
                ('description', models.TextField(verbose_name='описание места')),
            ],
            options={
                'verbose_name': 'место',
                'verbose_name_plural': 'места',
            },
        ),
        migrations.CreateModel(
            name='HabitTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='название')),
                ('description', models.TextField(verbose_name='описание')),
            ],
            options={
                'verbose_name': 'время выполнения',
                'verbose_name_plural': 'времена выполнения',
            },
        ),
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=150, verbose_name='действие')),
                ('nice_habit', models.CharField(max_length=150, verbose_name='приятная привычка')),
                ('related_habit', models.CharField(max_length=150, verbose_name='связанная полезная привычка')),
                ('period', models.CharField(choices=[('once_a_week', 'раз в неделю'), ('every_two_day', 'каждые два дня'), ('once_a_day', 'каждый день'), ('two_times_a_week', 'два раза в неделю')], default='once_a_day', max_length=150, verbose_name='периодичность')),
                ('reward', models.CharField(max_length=200, verbose_name='вознаграждение')),
                ('seconds_to_complete', models.PositiveIntegerField(verbose_name='время на выполнение в секундах')),
                ('is_public', models.BooleanField(default=False, verbose_name='признак публичной привычки')),
                ('place', models.ManyToManyField(to='habits.habitplace', verbose_name='место')),
                ('time_habit', models.ManyToManyField(to='habits.habittime', verbose_name='время')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='')),
            ],
            options={
                'verbose_name': 'привычка',
                'verbose_name_plural': 'привычки',
            },
        ),
    ]
