# Generated by Django 4.2.7 on 2024-03-06 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_remove_habit_nice_habit_habit_is_nice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='period',
            field=models.CharField(choices=[('once_a_week', 'раз в неделю'), ('two_times_a_week', 'два раза в неделю'), ('once_a_day', 'каждый день'), ('every_two_day', 'каждые два дня')], default='once_a_day', max_length=150, verbose_name='периодичность'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='related_habit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='habits.habit', verbose_name='связанная  привычка'),
        ),
    ]
