# Generated by Django 4.2.7 on 2024-03-06 17:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_alter_habit_period_alter_habit_related_habit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='period',
            field=models.CharField(choices=[('two_times_a_week', 'два раза в неделю'), ('every_two_day', 'каждые два дня'), ('once_a_week', 'раз в неделю'), ('once_a_day', 'каждый день')], default='once_a_day', max_length=150, verbose_name='периодичность'),
        ),
        migrations.RemoveField(
            model_name='habit',
            name='time_habit',
        ),
        migrations.DeleteModel(
            name='HabitTime',
        ),
        migrations.AddField(
            model_name='habit',
            name='time_habit',
            field=models.TimeField(default=datetime.datetime(2024, 3, 6, 22, 52, 23, 110850), verbose_name='время'),
        ),
    ]
