# Generated by Django 4.2.7 on 2024-03-08 06:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0005_alter_habit_period_remove_habit_time_habit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='period',
            field=models.CharField(choices=[('two_times_a_week', 'два раза в неделю'), ('every_two_day', 'каждые два дня'), ('once_a_day', 'каждый день'), ('once_a_week', 'раз в неделю')], default='once_a_day', max_length=150, verbose_name='периодичность'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='time_habit',
            field=models.TimeField(default=datetime.datetime(2024, 3, 8, 11, 5, 16, 326538), verbose_name='время'),
        ),
    ]
